# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3edf0c1f942dda6e0a8b81c6a1ce5f35363acd17694f7ea086eb50b43c9027a5a5860921c39cb91713203bbcfe1719385a020b2b6e08364039eebb271eab6ec

test:
  secret_key_base: c2abf4e648868ccc80b753f07509d983f807b572bdd3a07089183f2970a950efdfd084bf8ace549bc9532dc905540d38fb7dedd3b88e9a2a078ad447c65c41e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
